//! Template rendering: fill pre-tokenized spans with per-call values.
//!
//! Hot-path shape (docs/ARCHITECTURE.md §3): the template was tokenized once
//! at scenario load; rendering is slot filling into one buffer. Two
//! line-oriented fixups happen after the fill, both SIPp semantics:
//! `[last_X:]`/`[routes]` with nothing to substitute delete their whole line,
//! and `[len]` becomes the body length computed after all substitution.

use std::cell::RefCell;
use std::fmt::Write as _;

use sipr_net::Inbound;
use sipr_scenario::inject::InjectionFile;
use sipr_scenario::model::VarTable;
use sipr_scenario::template::{CryptoKw, Keyword, LineExpr, MsgTemplate, Span};

use crate::actions::VarStore;

/// Optional variable + auth resolution passed to the renderer.
#[derive(Clone, Copy)]
pub struct VarCtx<'a> {
    /// The call's variable store.
    pub store: &'a VarStore,
    /// The scenario's variable table (unused placeholder for symmetry).
    pub vars: &'a VarTable,
    /// A pending digest challenge captured by a `recv auth="true"`.
    pub challenge: Option<&'a sipr_auth::Challenge>,
    /// Auth username / password (`-au`/`-ap` or keyword params).
    pub auth_user: &'a str,
    pub auth_password: &'a str,
    /// Client nonce for digest (stable per call).
    pub cnonce: &'a str,
    /// The request method for the message being built.
    pub method: &'a str,
    /// The digest URI (request-URI shape).
    pub digest_uri: &'a str,
}

/// One local `a=crypto` slot: what the scenario's keywords selected.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct LocalCrypto {
    /// Suite chosen by a `cryptosuite…`/`ue…` keyword.
    pub suite: Option<String>,
    /// The master key generated by `cryptokeyparams…`.
    pub key: Option<sipr_media::MasterKey>,
    /// A `ue…` keyword: advertise the suite but authenticate only.
    pub unencrypted: bool,
}

/// A call's SRTP state: two local slots per media kind (SIPp's primary and
/// secondary `a=crypto` lines) and the peer's lines from its SDP.
#[derive(Debug, Clone, Default)]
pub struct CallCrypto {
    /// `[audio, video]` × `[slot 1, slot 2]`.
    pub local: [[LocalCrypto; 2]; 2],
    /// The peer's `a=crypto` lines, `[audio, video]`, primary first.
    pub remote: [Vec<sipr_media::sdp::CryptoAttr>; 2],
}

impl CallCrypto {
    /// The local slot for `video`/`slot` (slots are 1-based).
    pub fn local_mut(&mut self, video: bool, slot: u8) -> &mut LocalCrypto {
        &mut self.local[usize::from(video)][usize::from(slot.clamp(1, 2) - 1)]
    }

    /// The local slot, read-only.
    #[must_use]
    pub fn local(&self, video: bool, slot: u8) -> &LocalCrypto {
        &self.local[usize::from(video)][usize::from(slot.clamp(1, 2) - 1)]
    }

    /// Record the peer's lines for a media kind.
    pub fn set_remote(&mut self, video: bool, attrs: Vec<sipr_media::sdp::CryptoAttr>) {
        self.remote[usize::from(video)] = attrs;
    }

    /// SIPp's negotiation, distilled: no peer line → plain RTP; otherwise
    /// send under our slot whose suite the peer's PRIMARY line names (slot 1,
    /// or slot 2 if only that matches — SIPp's `swapCrypto`), and receive
    /// under the peer's primary line.
    ///
    /// # Errors
    ///
    /// A reason when the peer offered SRTP but we cannot honour it (no
    /// local key, unknown suite, undecodable key).
    pub fn negotiate(
        &self,
        video: bool,
    ) -> Result<Option<(sipr_media::SrtpContext, sipr_media::SrtpContext)>, String> {
        let Some(remote) = self.remote[usize::from(video)].first() else {
            return Ok(None);
        };
        let remote_suite = sipr_media::Suite::parse(&remote.suite)
            .ok_or_else(|| format!("peer's suite '{}' is not supported", remote.suite))?;
        let remote_key = sipr_media::MasterKey::from_sdes(&remote.key_params)
            .ok_or_else(|| "peer's inline key does not decode".to_owned())?;
        let slot1 = self.local(video, 1);
        let slot2 = self.local(video, 2);
        let local = if slot1.suite.as_deref() == Some(remote.suite.as_str()) || slot2.key.is_none()
        {
            slot1
        } else if slot2.suite.as_deref() == Some(remote.suite.as_str()) {
            slot2
        } else {
            slot1
        };
        let local_suite = local
            .suite
            .as_deref()
            .and_then(sipr_media::Suite::parse)
            .ok_or_else(|| "no local cryptosuite keyword was rendered".to_owned())?;
        let local_key = local
            .key
            .as_ref()
            .ok_or_else(|| "no local cryptokeyparams keyword was rendered".to_owned())?;
        let tx = sipr_media::SrtpContext::new(local_suite, local_key, local.unencrypted);
        let rx = sipr_media::SrtpContext::new(remote_suite, &remote_key, remote.unencrypted_srtp);
        Ok(Some((tx, rx)))
    }
}

/// Marker interpolated for `[len]`, patched after body length is known.
const LEN_MARKER: &str = "\u{7}SIPR_LEN\u{7}";
/// Marker appended when a line must be deleted (empty `[last_*]`/`[routes]`).
const KILL_MARKER: &str = "\u{7}SIPR_KILL\u{7}";

/// Everything the renderer may substitute for one message of one call.
#[derive(Clone)]
pub struct RenderCtx<'a> {
    /// `-s` service / called user part.
    pub service: &'a str,
    /// Remote target.
    pub remote_ip: &'a str,
    /// Remote port.
    pub remote_port: u16,
    /// Local bound IP.
    pub local_ip: &'a str,
    /// Local bound port.
    pub local_port: u16,
    /// Media address (`-mi`, default local IP) for `[media_ip]`.
    pub media_ip: &'a str,
    /// Base media port (`-mp`, default 6000) for `[media_port]`.
    pub media_port: u16,
    /// This call's allocated `[rtpstream_audio_port]` / `[rtpstream_video_port]`
    /// (0 when never allocated — the engine allocates before rendering).
    pub rtpstream_ports: [u16; 2],
    /// This call's SRTP state (keys generated before rendering).
    pub crypto: Option<&'a CallCrypto>,
    /// Transport token (`UDP` in v1).
    pub transport: &'a str,
    /// This call's Call-ID.
    pub call_id: &'a str,
    /// 1-based call number.
    pub call_number: u64,
    /// This call's 1-based user id (`-users` mode; 0 otherwise).
    pub user_id: u64,
    /// Configured `-users` count (0 when not in users mode).
    pub users_total: u64,
    /// Process id discriminator.
    pub pid: u32,
    /// Current CSeq counter value.
    pub cseq: u32,
    /// Step index (message index) being sent.
    pub msg_index: usize,
    /// Remote tag, once learned (renders `[peer_tag_param]`).
    pub peer_tag: Option<&'a str>,
    /// Captured Record-Route values (via `rrs`), top first.
    pub routes: &'a [String],
    /// Last received message (renders `[last_*]`, `[next_url]`).
    pub last: Option<&'a Inbound>,
    /// Variables + auth (present at M6; `None` renders `[$x]` empty).
    pub var_ctx: Option<VarCtx<'a>>,
    /// Injection files + this call's assigned line per file (`[fieldN]`).
    pub fields: FieldSource<'a>,
}

/// `-inf` files plus the current call's assigned line in each (parallel to
/// `files`). An out-of-range file/line/field renders empty, per SIPp.
///
/// Files sit behind `RefCell` because `insert`/`replace` actions mutate them
/// mid-run while `[fieldN]` reads them — all on the single engine thread, so
/// the borrows never overlap in time.
#[derive(Clone, Copy)]
pub struct FieldSource<'a> {
    /// Loaded injection files, in `-inf` order.
    pub files: &'a [RefCell<InjectionFile>],
    /// The call's chosen line per file (`None` = no line, e.g. USER mode).
    pub lines: &'a [Option<usize>],
}

impl FieldSource<'_> {
    /// No injection files.
    pub const EMPTY: Self = Self {
        files: &[],
        lines: &[],
    };

    /// Resolve a `file=` spec (a basename, or a numeric `-inf` index; `None`
    /// selects the first file) to an index into `files`.
    fn resolve_file(&self, spec: Option<&str>) -> Option<usize> {
        match spec {
            None => (!self.files.is_empty()).then_some(0),
            Some(s) => {
                if let Some(i) = self.files.iter().position(|c| c.borrow().name == s) {
                    return Some(i);
                }
                s.parse::<usize>().ok().filter(|&i| i < self.files.len())
            }
        }
    }

    /// The call's assigned line for file `fi`.
    fn default_line(&self, fi: usize) -> Option<usize> {
        self.lines.get(fi).copied().flatten()
    }

    /// Append field `index` of `line` in file `fi` to `out` (empty if absent).
    fn read(&self, fi: usize, line: usize, index: usize, out: &mut String) {
        if let Some(cell) = self.files.get(fi)
            && let Some(v) = cell.borrow().field(line, index)
        {
            out.push_str(v);
        }
    }

    /// `lookup`: matched line number for `key` in `file`, or `-1.0` on a miss.
    ///
    /// # Errors
    ///
    /// The file is unknown, or has no `-infindex`.
    pub fn lookup_line(&self, file: &str, key: &str) -> Result<f64, String> {
        let fi = self
            .resolve_file(Some(file))
            .ok_or_else(|| format!("lookup: unknown injection file '{file}'"))?;
        let cell = self.files[fi].borrow();
        if !cell.is_indexed() {
            return Err(format!("lookup: injection file '{file}' has no -infindex"));
        }
        #[allow(clippy::cast_precision_loss)]
        Ok(cell.lookup(key).map_or(-1.0, |l| l as f64))
    }

    /// `insert`: append a `;`-separated `value` line to `file`.
    ///
    /// # Errors
    ///
    /// The file is unknown.
    pub fn insert_line(&self, file: &str, value: &str) -> Result<(), String> {
        let fi = self
            .resolve_file(Some(file))
            .ok_or_else(|| format!("insert: unknown injection file '{file}'"))?;
        self.files[fi].borrow_mut().insert(value);
        Ok(())
    }

    /// `replace`: swap line `line` of `file` for a `;`-separated `value`.
    ///
    /// # Errors
    ///
    /// The file is unknown, or `line` is out of range.
    pub fn replace_line(&self, file: &str, line: usize, value: &str) -> Result<(), String> {
        let fi = self
            .resolve_file(Some(file))
            .ok_or_else(|| format!("replace: unknown injection file '{file}'"))?;
        self.files[fi].borrow_mut().replace(line, value)
    }
}

/// Rendering failure (unsupported keyword reached the renderer).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderError(pub String);

impl std::fmt::Display for RenderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "render: {}", self.0)
    }
}

/// Render a template to wire bytes.
///
/// # Errors
///
/// [`RenderError`] when a keyword cannot be produced — today only
/// `[authentication]` against an `AKAv1-MD5` challenge: missing or malformed
/// `aka_*` parameters, a malformed nonce, or a MAC that does not verify.
pub fn render(template: &MsgTemplate, ctx: &RenderCtx<'_>) -> Result<Vec<u8>, RenderError> {
    Ok(render_string(template, ctx)?.into_bytes())
}

/// Render a template to a `String`. Used for message bodies and for
/// expanding action message templates (log/assignstr) — the `extra` argument
/// lets callers substitute variables from an arbitrary store (M6 actions).
#[must_use]
pub fn render_to_string(
    template: &MsgTemplate,
    ctx: &RenderCtx<'_>,
    _extra: Option<(&VarStore, &VarTable)>,
) -> String {
    // The store already lives in ctx.var_ctx for the send path; `extra` is a
    // convenience for action expansion where ctx carries the same store.
    // Action templates never carry [authentication], so an error (the only
    // fallible keyword) cannot occur here; render what we can regardless.
    render_string(template, ctx).unwrap_or_default()
}

fn render_string(template: &MsgTemplate, ctx: &RenderCtx<'_>) -> Result<String, RenderError> {
    let mut out = String::with_capacity(512);
    for span in &template.spans {
        match span {
            Span::Lit(l) => out.push_str(l),
            Span::Kw(kw) => fill(kw, ctx, &mut out)?,
        }
    }
    // Delete lines that substituted to nothing (SIPp: "all bytes until the
    // end of the line are also discarded").
    if out.contains(KILL_MARKER) {
        out = out
            .split_inclusive('\n')
            .filter(|line| !line.contains(KILL_MARKER))
            .collect();
    }
    // Patch [len] with the body length (bytes after the header separator).
    if out.contains(LEN_MARKER) {
        let body_len = out.find("\r\n\r\n").map_or(0, |i| out.len() - (i + 4));
        out = out.replace(LEN_MARKER, &body_len.to_string());
    }
    Ok(out)
}

#[allow(clippy::too_many_lines)] // one arm per keyword; splitting hurts
fn fill(kw: &Keyword, ctx: &RenderCtx<'_>, out: &mut String) -> Result<(), RenderError> {
    match kw {
        Keyword::Service => out.push_str(ctx.service),
        Keyword::RemoteIp => push_ip_for_uri(out, ctx.remote_ip),
        Keyword::RemotePort => {
            let _ = write!(out, "{}", ctx.remote_port);
        }
        Keyword::LocalIp => push_ip_for_uri(out, ctx.local_ip),
        Keyword::LocalIpType => out.push_str(ip_type(ctx.local_ip)),
        Keyword::LocalPort => {
            let _ = write!(out, "{}", ctx.local_port);
        }
        Keyword::Transport => out.push_str(ctx.transport),
        Keyword::CallId => out.push_str(ctx.call_id),
        Keyword::CallNumber => {
            let _ = write!(out, "{}", ctx.call_number);
        }
        Keyword::UserId => {
            let _ = write!(out, "{}", ctx.user_id);
        }
        Keyword::Users => {
            let _ = write!(out, "{}", ctx.users_total);
        }
        Keyword::Cseq => {
            let _ = write!(out, "{}", ctx.cseq);
        }
        Keyword::Branch => {
            // SIPp-shaped: magic cookie + pid + call number + msg index.
            // Stable across retransmissions (buffers are resent verbatim),
            // distinct across transactions of one call.
            let _ = write!(
                out,
                "z9hG4bK-{}-{}-{}",
                ctx.pid, ctx.call_number, ctx.msg_index
            );
        }
        Keyword::MsgIndex => {
            let _ = write!(out, "{}", ctx.msg_index);
        }
        Keyword::Pid => {
            let _ = write!(out, "{}", ctx.pid);
        }
        Keyword::PeerTagParam => {
            if let Some(tag) = ctx.peer_tag {
                let _ = write!(out, ";tag={tag}");
            }
        }
        Keyword::Routes => {
            if ctx.routes.is_empty() {
                out.push_str(KILL_MARKER);
            } else {
                // Route set = captured Record-Route values, reversed (we are
                // the UAC; RFC 3261 §12.1.2).
                let mut first = true;
                for r in ctx.routes.iter().rev() {
                    if !first {
                        out.push_str("\r\n");
                    }
                    let _ = write!(out, "Route: {r}");
                    first = false;
                }
            }
        }
        Keyword::NextUrl => {
            // Contact URI of the last received message; fall back to the
            // original request URI shape.
            let contact_uri = ctx
                .last
                .and_then(|m| m.header("Contact"))
                .map(strip_angle_brackets);
            match contact_uri {
                Some(uri) => out.push_str(uri),
                None => {
                    let _ = write!(
                        out,
                        "sip:{}@{}:{}",
                        ctx.service, ctx.remote_ip, ctx.remote_port
                    );
                }
            }
        }
        Keyword::Len => out.push_str(LEN_MARKER),
        Keyword::MediaIp => out.push_str(ctx.media_ip),
        Keyword::MediaPort { auto, offset } => {
            let port = media_port_value(ctx.media_port, *auto, *offset, ctx.call_number);
            let _ = write!(out, "{port}");
        }
        Keyword::MediaIpType => out.push_str(ip_type(ctx.media_ip)),
        Keyword::RtpStreamPort { video, offset } => {
            let base = ctx.rtpstream_ports[usize::from(*video)];
            let _ = write!(out, "{}", base.saturating_add(*offset));
        }
        Keyword::Crypto {
            kw, slot, video, ..
        } => match kw {
            CryptoKw::Tag => {
                let _ = write!(out, "{slot}");
            }
            CryptoKw::Suite(s) => out.push_str(s),
            CryptoKw::Unencrypted(_) => out.push_str("UNENCRYPTED_SRTP"),
            CryptoKw::KeyParams => {
                if let Some(key) = ctx.crypto.and_then(|c| c.local(*video, *slot).key.as_ref()) {
                    out.push_str(&key.to_sdes());
                }
            }
        },
        Keyword::Field { index, file, line } => {
            if let Some(fi) = ctx.fields.resolve_file(file.as_deref()) {
                // No `line=` → the call's assigned line. With `line=`, an
                // invalid/negative value renders empty (SIPp sets line -1).
                let chosen = match line {
                    None => ctx.fields.default_line(fi),
                    Some(expr) => resolve_line_expr(expr, ctx),
                };
                if let Some(l) = chosen {
                    ctx.fields.read(fi, l, *index, out);
                }
            }
        }
        Keyword::Last(name) => {
            let lines = ctx.last.map(|m| m.header_lines(name)).unwrap_or_default();
            if lines.is_empty() {
                out.push_str(KILL_MARKER);
            } else {
                out.push_str(&lines.join("\r\n"));
            }
        }
        Keyword::Var(name) => {
            if let Some(vc) = &ctx.var_ctx {
                // Names were interned; look up by re-interning against the table.
                if let Some(id) = table_lookup(vc.vars, name) {
                    out.push_str(&vc.store.get(id).as_str());
                }
            }
        }
        Keyword::Authentication(raw_params) => {
            if let Some(vc) = &ctx.var_ctx {
                if let Some(ch) = vc.challenge {
                    // SIPp renders every parameter as a sub-message, so
                    // `username=[field0]` or `aka_K=[$k]` work.
                    let rendered = render_auth_params(raw_params, ctx);
                    let params = &rendered;
                    let user = param_or(params, "username", vc.auth_user);
                    let pass = param_or(params, "password", vc.auth_password);
                    let aka = if ch.algorithm == sipr_auth::Algorithm::AkaV1Md5 {
                        Some(aka_keys(params, pass)?)
                    } else {
                        None
                    };
                    let cred = sipr_auth::Credentials {
                        username: user,
                        password: pass,
                        method: vc.method,
                        uri: vc.digest_uri,
                        cnonce: vc.cnonce,
                        nc: 1,
                        aka,
                    };
                    // authorization_header returns "Name: Digest ..."; the
                    // scenario supplies the header name context, so emit only
                    // the value after the colon.
                    let line = sipr_auth::authorization_header(ch, &cred)
                        .map_err(|e| RenderError(format!("[authentication]: {e}")))?;
                    let value = line.split_once(": ").map_or(line.as_str(), |(_, v)| v);
                    out.push_str(value);
                }
            }
        }
        Keyword::Unknown(u) => {
            // Tokenizer emits unknown keywords as literals; reaching here is
            // a bug upstream, but render verbatim rather than dying.
            let _ = write!(out, "[{u}]");
        }
    }
    Ok(())
}

/// The AKA secrets from `[authentication aka_K= aka_OP=|aka_OPc= aka_AMF=
/// aka_sqn= aka_resync=]` (SIPp's parameter names; `aka_OPc`, `aka_sqn`
/// (the client's SQN_MS, 6 bytes) and `aka_resync` (force AUTS) are sipr
/// additions — SIPp only takes OP and never resynchronises). Values are `0x`-prefixed hex of exactly the right length, or raw
/// bytes of that length. Without `aka_K`, SIPp uses the password's first
/// 16 bytes as K (documented); that fallback is honoured when the password
/// is long enough, otherwise it is an error rather than a read past the end.
fn aka_keys(
    params: &[(String, String)],
    password: &str,
) -> Result<sipr_auth::AkaKeys, RenderError> {
    let get = |key: &str| {
        params
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.as_str())
    };
    let k: [u8; 16] = match get("aka_K") {
        Some(v) => parse_secret(v, "aka_K")?,
        None => {
            let bytes = password.as_bytes();
            if bytes.len() < 16 {
                return Err(RenderError(
                    "[authentication]: AKAv1-MD5 needs aka_K=0x<32 hex> (SIPp's fallback to \
                     the password needs a password of at least 16 bytes)"
                        .into(),
                ));
            }
            let mut out = [0u8; 16];
            out.copy_from_slice(&bytes[..16]);
            out
        }
    };
    let opc: [u8; 16] = match (get("aka_OPc"), get("aka_OP")) {
        (Some(v), _) => parse_secret(v, "aka_OPc")?,
        (None, Some(v)) => {
            let op: [u8; 16] = parse_secret(v, "aka_OP")?;
            sipr_auth::milenage::opc(&k, &op)
        }
        (None, None) => {
            return Err(RenderError(
                sipr_auth::AuthError::AkaKeysMissing.to_string(),
            ));
        }
    };
    let amf: Option<[u8; 2]> = match get("aka_AMF") {
        Some(v) => Some(parse_secret(v, "aka_AMF")?),
        None => None,
    };
    // sipr additions for resynchronisation testing (SIPp never sends AUTS).
    let sqn_ms: Option<[u8; 6]> = match get("aka_sqn") {
        Some(v) => Some(parse_secret(v, "aka_sqn")?),
        None => None,
    };
    let force_resync = match get("aka_resync") {
        None => false,
        Some(v) => match v.trim() {
            "1" | "true" | "yes" => true,
            "0" | "false" | "no" => false,
            other => {
                return Err(RenderError(format!(
                    "[authentication]: aka_resync= must be 0/1 (got '{other}')"
                )));
            }
        },
    };
    Ok(sipr_auth::AkaKeys {
        k,
        opc,
        amf,
        sqn_ms,
        force_resync,
    })
}

/// `0x`-prefixed hex of exactly `N` bytes, or `N` raw bytes.
fn parse_secret<const N: usize>(value: &str, name: &str) -> Result<[u8; N], RenderError> {
    let mut out = [0u8; N];
    if let Some(hex) = value
        .strip_prefix("0x")
        .or_else(|| value.strip_prefix("0X"))
    {
        if hex.len() != 2 * N || !hex.bytes().all(|b| b.is_ascii_hexdigit()) {
            return Err(RenderError(format!(
                "[authentication]: {name}= must be 0x followed by {} hex digits ({N} bytes), got \
                 {} characters",
                2 * N,
                hex.len()
            )));
        }
        for (i, b) in out.iter_mut().enumerate() {
            *b = u8::from_str_radix(&hex[2 * i..2 * i + 2], 16).unwrap_or(0);
        }
        return Ok(out);
    }
    if value.len() != N {
        return Err(RenderError(format!(
            "[authentication]: {name}= must be {N} raw bytes or 0x + {} hex digits, got {} bytes",
            2 * N,
            value.len()
        )));
    }
    out.copy_from_slice(value.as_bytes());
    Ok(out)
}

fn table_lookup(vars: &VarTable, name: &str) -> Option<usize> {
    (0..vars.len()).find(|&i| vars.name(i) == name)
}

/// Resolve a `[fieldN line=...]` selector to a concrete line. A `line=[$var]`
/// that is unset, non-numeric, or negative yields `None` (empty field), which
/// is how a `lookup` miss (variable = -1) collapses to no output.
fn resolve_line_expr(expr: &LineExpr, ctx: &RenderCtx<'_>) -> Option<usize> {
    match expr {
        LineExpr::Literal(n) => Some(*n),
        LineExpr::Var(name) => {
            let vc = ctx.var_ctx.as_ref()?;
            let id = table_lookup(vc.vars, name)?;
            let n = vc.store.get(id).as_num();
            if n < 0.0 {
                None
            } else {
                #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
                Some(n as usize)
            }
        }
    }
}

/// Expand keywords inside `[authentication]` parameter values (SIPp renders
/// each as a sub-message). Values without `[` pass through untouched; a
/// nested `[authentication]` is not expanded.
fn render_auth_params(params: &[(String, String)], ctx: &RenderCtx<'_>) -> Vec<(String, String)> {
    params
        .iter()
        .map(|(k, v)| {
            if !v.contains('[') || v.contains("[authentication") {
                return (k.clone(), v.clone());
            }
            let mut scratch = sipr_scenario::diag::Diagnostics::new("authentication");
            let sub = sipr_scenario::template::tokenize(v, 0, &mut scratch);
            (k.clone(), render_to_string(&sub, ctx, None))
        })
        .collect()
}

fn param_or<'a>(params: &'a [(String, String)], key: &str, default: &'a str) -> &'a str {
    params
        .iter()
        .find(|(k, _)| k == key)
        .map_or(default, |(_, v)| v.as_str())
}

/// The port `[media_port]` / `[auto_media_port]` (+`offset`) renders for
/// call `call_number`, and therefore the local port its RTP is sent from.
/// `auto` reserves a 4-port block per call and wraps after 2500 calls, as
/// SIPp's `auto_media_port` does (`call.cpp`: `4 * (number - 1) % 10000`).
#[must_use]
pub fn media_port_value(base: u16, auto: bool, offset: u16, call_number: u64) -> u16 {
    let block = if auto {
        (4 * call_number.saturating_sub(1)) % 10_000
    } else {
        0
    };
    let port = u64::from(base) + block + u64::from(offset);
    u16::try_from(port).unwrap_or(u16::MAX)
}

fn ip_type(ip: &str) -> &'static str {
    if ip.contains(':') { "6" } else { "4" }
}

/// Emit an IP for use inside a SIP URI / Via: an IPv6 address is bracketed
/// (`[2001:db8::1]`), matching SIPp's `local_ip_w_brackets`. `[media_ip]` stays
/// raw because SDP `c=`/`o=` addresses are never bracketed.
fn push_ip_for_uri(out: &mut String, ip: &str) {
    if ip.contains(':') && !ip.starts_with('[') {
        out.push('[');
        out.push_str(ip);
        out.push(']');
    } else {
        out.push_str(ip);
    }
}

fn strip_angle_brackets(contact: &str) -> &str {
    let inner = contact.find('<').and_then(|start| {
        contact[start..]
            .find('>')
            .map(|end| &contact[start + 1..start + end])
    });
    inner
        .unwrap_or(contact)
        .split(';')
        .next()
        .unwrap_or(contact)
}

#[cfg(test)]
mod tests {
    use super::*;
    use sipr_scenario::model::Step;

    fn ctx<'a>(last: Option<&'a Inbound>) -> RenderCtx<'a> {
        RenderCtx {
            service: "service",
            remote_ip: "10.0.0.2",
            remote_port: 5060,
            local_ip: "10.0.0.1",
            local_port: 5061,
            media_ip: "10.0.0.1",
            media_port: 6000,
            rtpstream_ports: [0, 0],
            crypto: None,
            transport: "UDP",
            call_id: "1-99@10.0.0.1",
            call_number: 1,
            user_id: 0,
            users_total: 0,
            pid: 99,
            cseq: 1,
            msg_index: 0,
            peer_tag: None,
            routes: &[],
            last,
            var_ctx: None,
            fields: crate::render::FieldSource::EMPTY,
        }
    }

    fn uac_invite_template() -> MsgTemplate {
        let sc = sipr_scenario::compile("uac", sipr_scenario::embedded("uac").unwrap())
            .scenario
            .unwrap();
        match &sc.steps[0] {
            Step::Send(s) => s.template.clone(),
            _ => panic!("step 0 must be the INVITE"),
        }
    }

    #[test]
    fn renders_embedded_invite_with_correct_len() {
        let bytes = render(&uac_invite_template(), &ctx(None)).unwrap();
        let text = String::from_utf8(bytes).unwrap();
        assert!(
            text.starts_with("INVITE sip:service@10.0.0.2:5060 SIP/2.0\r\n"),
            "{text}"
        );
        assert!(text.contains("Via: SIP/2.0/UDP 10.0.0.1:5061;branch=z9hG4bK-99-1-0\r\n"));
        assert!(text.contains("Call-ID: 1-99@10.0.0.1\r\n"));
        let (head, body) = text.split_once("\r\n\r\n").expect("separator");
        let len: usize = head
            .lines()
            .find_map(|l| l.strip_prefix("Content-Length: "))
            .expect("length header")
            .parse()
            .expect("numeric");
        assert_eq!(len, body.len(), "[len] must equal body bytes:\n{text}");
        assert!(body.starts_with("v=0\r\n"));
        assert!(
            body.contains("c=IN IP4 10.0.0.1"),
            "media placeholders fill"
        );
    }

    #[test]
    fn peer_tag_param_renders_or_vanishes() {
        let t = sipr_scenario::compile("uac", sipr_scenario::embedded("uac").unwrap())
            .scenario
            .unwrap();
        let Step::Send(ack) = &t.steps[5] else {
            panic!("step 5 must be the ACK");
        };
        let no_tag = String::from_utf8(render(&ack.template, &ctx(None)).unwrap()).unwrap();
        assert!(no_tag.contains("To: service <sip:service@10.0.0.2:5060>\r\n"));
        let mut c = ctx(None);
        c.peer_tag = Some("as7d9");
        let tagged = String::from_utf8(render(&ack.template, &c).unwrap()).unwrap();
        assert!(tagged.contains("To: service <sip:service@10.0.0.2:5060>;tag=as7d9\r\n"));
    }

    #[test]
    fn empty_last_header_deletes_the_whole_line() {
        let out = sipr_scenario::compile(
            "t",
            r#"<scenario name="t">
                 <recv request="OPTIONS"/>
                 <send><![CDATA[
                   SIP/2.0 200 OK
                   [last_Via:]
                   [last_Record-Route:]
                   [last_Call-ID:]
                   Content-Length: 0

                 ]]></send>
               </scenario>"#,
        );
        let sc = out.scenario.unwrap();
        let Step::Send(s) = &sc.steps[1] else {
            panic!("not send");
        };
        let inbound = Inbound::parse(
            b"OPTIONS sip:x SIP/2.0\r\nVia: SIP/2.0/UDP h:1;branch=z9\r\nCall-ID: abc\r\n\r\n",
        )
        .unwrap();
        let text = String::from_utf8(render(&s.template, &ctx(Some(&inbound))).unwrap()).unwrap();
        assert!(text.contains("Via: SIP/2.0/UDP h:1;branch=z9\r\n"));
        assert!(text.contains("Call-ID: abc\r\n"));
        assert!(
            !text.contains("Record-Route"),
            "absent header must delete its line:\n{text}"
        );
    }

    #[test]
    fn field_source_resolve_lookup_insert_replace() {
        use sipr_scenario::inject::InjectionFile;
        let mut f =
            InjectionFile::parse("users.csv", "SEQUENTIAL\nalice;1001\nbob;1002\n").unwrap();
        f.build_index(0);
        let files = vec![RefCell::new(f)];
        let fs = FieldSource {
            files: &files,
            lines: &[Some(0)],
        };

        // Resolve by name, by numeric index, and default; unknown -> None.
        assert_eq!(fs.resolve_file(Some("users.csv")), Some(0));
        assert_eq!(fs.resolve_file(Some("0")), Some(0));
        assert_eq!(fs.resolve_file(None), Some(0));
        assert_eq!(fs.resolve_file(Some("nope")), None);

        // lookup: hit, miss (-1), unknown-file error.
        assert_eq!(fs.lookup_line("users.csv", "bob").unwrap(), 1.0);
        assert_eq!(fs.lookup_line("users.csv", "ghost").unwrap(), -1.0);
        assert!(fs.lookup_line("missing", "x").is_err());

        // insert then look up the new row.
        fs.insert_line("users.csv", "carol;1003").unwrap();
        assert_eq!(fs.lookup_line("users.csv", "carol").unwrap(), 2.0);

        // replace row 0: old key drops, new key indexes, read reflects it.
        fs.replace_line("users.csv", 0, "amir;1000").unwrap();
        assert_eq!(fs.lookup_line("users.csv", "alice").unwrap(), -1.0);
        assert_eq!(fs.lookup_line("users.csv", "amir").unwrap(), 0.0);
        let mut out = String::new();
        fs.read(0, 0, 0, &mut out);
        assert_eq!(out, "amir");
        assert!(
            fs.replace_line("users.csv", 99, "z").is_err(),
            "out of range"
        );

        // lookup on an unindexed file errors (SIPp: "Invalid Index File").
        let g = InjectionFile::parse("plain.csv", "SEQUENTIAL\nx;y\n").unwrap();
        let files2 = vec![RefCell::new(g)];
        let fs2 = FieldSource {
            files: &files2,
            lines: &[Some(0)],
        };
        assert!(fs2.lookup_line("plain.csv", "x").is_err());
    }

    #[test]
    fn ipv6_ip_is_bracketed_in_uri_but_media_stays_raw() {
        let mut c = ctx(None);
        c.local_ip = "2001:db8::1";
        c.media_ip = "2001:db8::1";
        c.remote_ip = "2001:db8::2";
        let text = String::from_utf8(render(&uac_invite_template(), &c).unwrap()).unwrap();
        // Request-URI and Via bracket the IPv6 address (SIPp local_ip_w_brackets).
        assert!(text.contains("@[2001:db8::2]:5060"), "request-URI:\n{text}");
        assert!(
            text.contains("UDP [2001:db8::1]:5061;branch="),
            "Via:\n{text}"
        );
        // SDP address type is 6, and the c= line keeps the raw (unbracketed) IP.
        assert!(text.contains("c=IN IP6 2001:db8::1"), "SDP c=:\n{text}");
    }

    #[test]
    fn branch_differs_per_msg_index_only() {
        let t = uac_invite_template();
        let mut a = ctx(None);
        a.msg_index = 0;
        let mut b = ctx(None);
        b.msg_index = 7;
        let ra = String::from_utf8(render(&t, &a).unwrap()).unwrap();
        let rb = String::from_utf8(render(&t, &b).unwrap()).unwrap();
        assert!(ra.contains("branch=z9hG4bK-99-1-0"));
        assert!(rb.contains("branch=z9hG4bK-99-1-7"));
    }
}
